const mocks = {
  schoolName: 'TestingSchool',
  address: '18 Ivo Street Kuma Estate, Abuja, Nigeria',
  address2: '1 Noble Street Elekwa Estate, Port Harcourt, Nigeria',
  schoolWebsite: 'https://www.google.com',
  semesterName: 'Semester',
  semesterName2: 'Semester 2',
  firstName: 'Orseer',
  firstName2: 'Orsi',
  lastName: 'Sela',
  lastName2: 'Selako',
  maleGender: 'MALE',
  femaleGender: 'FEMALE',
  qualification: 'B.Sc. Business Administration',
  previousWorkPlace: 'Department of petroleum resources',
  previousSchool: 'Department of petroleum resources',
  language: 'English',
  stateOfOrigin: 'Benue state',
  countryCode: 'NG',
  country: 'Nigeria',
  className: 'Software engineering or JS1A',
  classDescription: 'This is known as departments in Universities',
  classColour: 'BLUE',
  classCode: 'JS1',
  classLevel: 100,
  subjectName: 'Mathematics or Logic gates',
  subjectCode: 'MTH',
  subjectDescription: 'Known as subject or course',
  creditUnit1: 1,
  year: 1,
  semester1: 1,
  semester2: 2,
  pdfFileType: 'PDF',
  imageFileType: 'JPG',
  noteDescription: 'This is the description of chike and the river',
  noteTopic: 'Chike and the river',
  newsDescription: 'This is the description of chike and the river',
  newsTopic: 'Chike and the river',
  assessmentDescription: 'This is the description of chike and the river',
  assessmentTopic: 'Chike and the river',
  assessmentOverall: 20,
  points: 5,
  points2: 4,
  topMargin: 100,
  topMargin2: 74.99,
  bottomMargin: 75,
  bottomMargin2: 60,
  gradeName: 'Excellent',
  gradeName2: 'Very good',
  gradeCode: 'A',
  gradeCode2: 'B',
  periodDescription: 'About Covalent Bonds',
  periodName: 'Thursday-maths',
};

export default mocks;
